# BlackKingShader Yapilandirma Dosyasi

# Video Ayarlari > Shader Secenekleri ekraninda slider olarak gorunecekler
sliders=SHARPEN_INTENSITY DARK_THRESHOLD LIGHT_STRENGTH SATURATION VIGNETTE_STRENGTH CHROMA_STRENGTH DAYNIGHT_STRENGTH UNDERWATER_CLARITY

# Ana ekranda hangi secenekler, hangi sirayla gorunecek
screen=SHARPEN_INTENSITY DARK_THRESHOLD LIGHT_STRENGTH SATURATION VIGNETTE_STRENGTH CHROMA_STRENGTH DAYNIGHT_STRENGTH UNDERWATER_CLARITY
